Bugfix-44451 : Throw error message for the given condition
tilangapramithvidusara/NestedValidationRulePCF pull request #25
Opened 2024-03-04 03:56 UTC by say1bt

User cannot save if the field name is same as the current question name in expression builder.

2024-03-04 09:31 UTC, tilangapramithvidusara commented on ValidationRules/src/Features/index.tsx
> +  // const [_nestedRows, _setNestedRows] = useState<any>([
remove those commented lines

2024-03-04 09:32 UTC, tilangapramithvidusara commented on ValidationRules/src/Features/index.tsx
> +  // const [currentQuestionDetails, setCurrentQuestionDetails] = useState<any>({
remove those comments

2024-03-04 09:32 UTC, tilangapramithvidusara commented on ValidationRules/src/Features/index.tsx
> +      console.log(
remove consoles

2024-03-04 09:33 UTC, tilangapramithvidusara commented on ValidationRules/src/Features/index.tsx
> +      console.log(
remove consoles

2024-03-04 09:34 UTC, tilangapramithvidusara commented on ValidationRules/src/Features/index.tsx
> +                              logicalName: "Show",
add hard coded values as constants

2024-03-04 09:34 UTC, tilangapramithvidusara commented on ValidationRules/src/Features/index.tsx
> +                            "OutPutDoc:Show": {
add hard coded values as constants

2024-03-04 09:34 UTC, tilangapramithvidusara commented on ValidationRules/src/Features/index.tsx
> +                          logicalName: "minMax",
add hard coded values as constants

2024-03-04 09:35 UTC, tilangapramithvidusara commented on ValidationRules/src/Features/index.tsx
> +                  type: "CLE_Q",
add hard coded values as constants

2024-03-04 09:35 UTC, tilangapramithvidusara commented on ValidationRules/src/Features/index.tsx
> +                    type: "VAL_Q",
add hard coded values as constants

2024-03-04 09:35 UTC, tilangapramithvidusara commented on ValidationRules/src/Features/index.tsx
> +                    type: "MAT_F",
add hard coded values as constants

2024-03-04 09:35 UTC, tilangapramithvidusara commented on ValidationRules/src/Features/index.tsx
> +                  type: "ADD_V",
add hard coded values as constants

2024-03-04 09:36 UTC, tilangapramithvidusara commented on ValidationRules/src/Features/index.tsx
> +    console.log("_visibilityAndDocOutput", _visibilityAndDocOutput);
if this console is not useful then remove it

2024-03-04 09:37 UTC, tilangapramithvidusara commented on ValidationRules/src/Features/index.tsx
> +          let visibilityAndDocRuleOutput = dbData?.visibilityAndDocRuleOutput
if this value not change after define put it as const

2024-03-04 09:37 UTC, tilangapramithvidusara commented on ValidationRules/src/Features/index.tsx
> +                            "OutPutDoc:Show": {
add hard coded values as constants

2024-03-04 09:38 UTC, tilangapramithvidusara commented on ValidationRules/src/Features/index.tsx
> +    if (currentPossitionDetails?.currentPosition === "chapter") {
add hard coded values as constants

2024-03-04 09:38 UTC, tilangapramithvidusara commented on ValidationRules/src/Features/index.tsx
> +    } else if (currentPossitionDetails?.currentPosition === "question") {
add hard coded values as constants

2024-03-04 09:38 UTC, tilangapramithvidusara commented on ValidationRules/src/Features/index.tsx
> +      (currentPossitionDetails?.currentPosition === "chapter" ||
add hard coded values as constants

2024-03-04 09:38 UTC, tilangapramithvidusara commented on ValidationRules/src/Features/index.tsx
> +      currentPossitionDetails?.currentPosition === "question"
add hard coded values as constants

2024-03-04 09:39 UTC, tilangapramithvidusara commented on ValidationRules/src/Features/index.tsx
> +    if (currentPossitionDetails?.currentPosition === "question") {
add hard coded values as constants

2024-03-04 09:39 UTC, tilangapramithvidusara commented on ValidationRules/src/Features/index.tsx
> +    } else if (currentPossitionDetails?.currentPosition === "chapter") {
add hard coded values as constants

2024-03-04 10:19 UTC, tilangapramithvidusara requested changes

2024-03-04 10:19 UTC, tilangapramithvidusara commented on ValidationRules/src/Features/rowContainer.tsx
>        let newRow = {
define this in common file as common variable

2024-03-04 10:19 UTC, tilangapramithvidusara commented on ValidationRules/src/Features/rowContainer.tsx
> +                  typeof fieldValue?.input === "string"
add hard coded values as constants

2024-03-04 10:19 UTC, tilangapramithvidusara commented on ValidationRules/src/Features/rowContainer.tsx
> +    if (fieldValue?.fieldName === "expression") {
add hard coded values as constants

2024-03-04 10:19 UTC, tilangapramithvidusara commented on ValidationRules/src/Features/rowContainer.tsx
> +                "error",
add hard coded values as constants

2024-03-04 10:19 UTC, tilangapramithvidusara commented on ValidationRules/src/Features/rowContainer.tsx
>        let newRow = {
get this from previously i mentioned file

2024-03-04 10:19 UTC, tilangapramithvidusara commented on ValidationRules/src/Features/rowContainer.tsx
> -          field: '',
reffer previous mentions value

2024-03-04 10:19 UTC, tilangapramithvidusara commented on ValidationRules/src/Features/rowContainer.tsx
> +      console.error("Error fetching data:", error);
handle this error properly

2024-03-04 10:19 UTC, tilangapramithvidusara commented on ValidationRules/src/Features/rowContainer.tsx
> +          _minMaxDbFormarFields?.exp[""]?.length
add hard coded values as constants

2024-03-04 10:19 UTC, tilangapramithvidusara commented on ValidationRules/src/Features/rowContainer.tsx
> +              type: "MINIMUM_LENGTH",
add hard coded values as constants

2024-03-04 10:19 UTC, tilangapramithvidusara commented on ValidationRules/src/Features/rowContainer.tsx
> +              type: "MAXIMUM_LENGTH",
add hard coded values as constants

2024-03-04 10:19 UTC, tilangapramithvidusara commented on ValidationRules/src/Features/rowContainer.tsx
> +              type: "MINIMUM",
add hard coded values as constants

2024-03-04 10:19 UTC, tilangapramithvidusara commented on ValidationRules/src/Features/rowContainer.tsx
> +              type: "MAXIMUM",
add hard coded values as constants

2024-03-05 04:27 UTC, anujshashimal1bt approved these changes

2024-03-05 04:27 UTC, merged